export const GET_PROJECTS = 'GET_PROJECTS'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const ADD_PROJECT = 'ADD_PROJECT'
export const SEND_MAIL = 'SEND_MAIL'
export const RESET_MAIL = 'RESET_MAIL'
export const SAVE_SETTING = 'SAVE_SETTING'
export const GET_SETTING = 'GET_SETTING'
